version: '2'
services:
  influxdb:
    image: influxdb:1.2.0
    ports:
    - "8086:8086"
    - "2003:2003"
    volumes:
    - ./data/influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana:4.1.1
    ports:
    - "3000:3000"
    volumes:
    - ./data/grafana:/var/lib/grafana
    links:
    - influxdb
